#pragma once
#include <opencv2/objdetect/objdetect.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/features2d.hpp>
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <map>
#include <vector>
#include <string>
#include <math.h>

/**
* A representation of the different types of blurs that can be used.
*
*/
enum BlurType {
	BOX, GAUSSIAN, MEDIAN, BILATERAL
};
/**
* CargoGripPipeline class.
* 
* An OpenCV pipeline generated by GRIP.
*/
class CargoGripPipeline {
	private:
		cv::Mat blurOutput;
		cv::Mat hsvThresholdOutput;
		std::vector<cv::KeyPoint> findBlobsOutput;
		void blur(cv::Mat &, BlurType &, double , cv::Mat &);
		void hsvThreshold(cv::Mat &, double [], double [], double [], cv::Mat &);
		void findBlobs(cv::Mat &, double , double [], bool , std::vector<cv::KeyPoint> &);
		bool compareBlob(cv::KeyPoint a, cv::KeyPoint b);

	public:
		CargoGripPipeline();
		void Process(cv::Mat& source0);
		cv::Mat* GetBlurOutput();
		cv::Mat* GetHsvThresholdOutput();
		std::vector<cv::KeyPoint>* GetFindBlobsOutput();
};